wallpaper {
    monitor = DP-1
    path = /home/martin/Pictures/ArtemisII/
    fit_mode = cover
    # order = random
}

wallpaper {
    monitor = HDMI-A-2
    path = /home/martin/Pictures/ArtemisII/
    fit_mode = cover
    # order = random
}
